import 'package:flutter/material.dart';

enum AppLanguage {
  tr,
  en,
}

class AppLanguageController extends ValueNotifier<AppLanguage> {
  AppLanguageController() : super(AppLanguage.tr);

  void setLanguage(AppLanguage language) {
    value = language;
  }
}

class AppLanguageScope extends InheritedNotifier<AppLanguageController> {
  const AppLanguageScope({
    required AppLanguageController controller,
    required super.child,
    super.key,
  }) : super(notifier: controller);

  static AppLanguageController controllerOf(BuildContext context) {
    final scope =
        context.dependOnInheritedWidgetOfExactType<AppLanguageScope>();
    assert(scope != null, 'AppLanguageScope not found');
    return scope!.notifier!;
  }

  static AppLanguage languageOf(BuildContext context) {
    return controllerOf(context).value;
  }
}

String t(BuildContext context, String key) {
  final language = AppLanguageScope.languageOf(context);
  final table = language == AppLanguage.tr ? _tr : _en;
  return table[key] ?? _en[key] ?? key;
}

const _tr = {
  'appName': 'DollDex Collector',
  'notifications': 'Bildirimler',
  'social': 'Sosyal',
  'theme': 'Tema',
  'catalog': 'Katalog',
  'collection': 'Koleksiyon',
  'profile': 'Profil',
  'pro': 'Pro',
  'admin': 'Admin',
  'catalogSubtitle': 'Karakterler, bebekler, setler, petler ve aksesuarlar tek yerde.',
  'searchHint': 'Karakter, set veya parça ara',
  'characters': 'Karakterler',
  'all': 'Tümü',
  'filter': 'Filtrele',
  'cancel': 'Vazgeç',
  'delete': 'Sil',
  'allConditions': 'Tüm durumlar',
  'dolls': 'Bebekler',
  'sets': 'Setler',
  'pets': 'Petler',
  'accessories': 'Aksesuarlar',
  'owned': 'Sahibim',
  'want': 'İstiyorum',
  'report': 'Raporla',
  'addToCollection': 'Koleksiyona ekle',
  'comments': 'Yorumlar',
  'commentHint': 'Not yaz veya ilgili parça linki yapıştır',
  'postComment': 'Yorum gönder',
  'reportComment': 'Yorumu raporla',
  'collectionSubtitle': 'Sahip olunan, istenen, takaslık ve satılık parçaları takip et.',
  'wanted': 'İstenen',
  'trade': 'Takas',
  'selling': 'Satılık',
  'yourShelfReady': 'Rafın hazır',
  'yourShelfBody': 'Koleksiyonunu oluşturmaya başlamak için katalogdan parça ekle.',
  'quantityShort': 'Adet',
  'removeFromCollection': 'Koleksiyondan kaldır',
  'removeCollectionConfirm': 'Bu parçayı koleksiyonundan kaldırmak istediğine emin misin?',
  'noCollectionFilterResults': 'Bu filtrede parça yok',
  'noCollectionFilterResultsBody': 'Başka bir koleksiyon durumu seç.',
  'noCatalogResults': 'Sonuç bulunamadı',
  'noCatalogResultsBody': 'Aramayı veya filtreleri değiştirerek tekrar dene.',
  'profileSubtitle': 'Herkese açık vitrin, gizlilik ayarları ve hesap araçları.',
  'profileStats': 'Profil özeti',
  'profileShowcaseTitle': 'Profil vitrini',
  'profileShowcaseEmpty': 'Koleksiyonundan parçalar ekledikçe burada görünür.',
  'collectorAccount': 'Koleksiyoner hesabı',
  'signInBody': 'Koleksiyonunu, istek listeni ve profilini senkronize etmek için giriş yap.',
  'continueGoogle': 'Google ile devam et',
  'accountTools': 'Hesap araçları',
  'privacyPolicy': 'Gizlilik politikası',
  'privacyRequired': 'Google Play ve web için gerekli.',
  'termsOfUse': 'Kullanım koşulları',
  'termsRequired': 'Uygulama kuralları ve kullanıcı sorumlulukları.',
  'deleteAccount': 'Hesap silme talebi',
  'deleteRequired': 'Uygulama içinde ve webde gerekli.',
  'completeProfileRequired': 'Profil kurulumu gerekli',
  'completeProfileBody': 'Sosyal özellikleri kullanmadan önce benzersiz kullanıcı adını ve yaş uygunluğunu tamamla.',
  'username': 'Kullanıcı adı',
  'usernameRules': '3-15 karakter: küçük harf, rakam ve alt çizgi.',
  'usernameInvalid': 'Kullanıcı adı 3-15 karakter olmalı; sadece harf, rakam ve alt çizgi kullanılabilir.',
  'usernameTaken': 'Bu kullanıcı adı alınmış.',
  'usernameChangeWarning': 'Kullanıcı adını belirledikten sonra 6 ayda yalnızca bir kez değiştirebilirsin.',
  'usernameChangeLocked': 'Kullanıcı adı 6 ayda bir kez değiştirilebilir.',
  'birthYear': 'Doğum yılı',
  'birthYearInvalid': 'Geçerli bir doğum yılı gir.',
  'ageRequirement': 'DollDex Collector kullanmak için en az 13 yaşında olmalısın.',
  'ageTooYoung': 'Yaş sınırı nedeniyle hesap kurulumu tamamlanamaz.',
  'acceptPrivacy': 'Gizlilik politikasını okudum ve kabul ediyorum.',
  'acceptTerms': 'Kullanım koşullarını okudum ve kabul ediyorum.',
  'acceptPoliciesRequired': 'Devam etmek için gizlilik politikası ve kullanım koşullarını kabul etmelisin.',
  'saveProfile': 'Profili tamamla',
  'profileSaved': 'Profil tamamlandı.',
  'profileSaveFailed': 'Profil kaydedilemedi:',
  'avatarStudio': 'Avatar stüdyosu',
  'avatarStudioBody': 'Avatarlar ve neon çerçeveler sadece Pro üyelerimize özeldir. Gotik profilini özelleştir!',
  'proFrames': 'Pro çerçeve renkleri',
  'proFramesLocked': 'Çerçeve renkleri Pro kullanıcılar için açıktır.',
  'deleteReason': 'Silme nedeni veya not',
  'sendDeleteRequest': 'Silme talebi gönder',
  'deleteRequestSaved': 'Hesap silme talebin kaydedildi.',
  'deleteRequestFailed': 'Silme talebi gönderilemedi:',
  'socialSubtitle': 'Kullanıcı ara, arkadaş ekle, engelle, mesaj gönder ve genel sohbete katıl.',
  'socialSignInRequired': 'Sosyal özellikleri kullanmak için Google hesabınla giriş yapmalısın.',
  'userSearch': 'Kullanıcı arama',
  'searchUsername': 'Kullanıcı adı ara',
  'search': 'Ara',
  'noUsersFound': 'Henüz kullanıcı bulunamadı.',
  'socialSearchFailed': 'Kullanıcı arama başarısız:',
  'sendFriendRequest': 'Arkadaş isteği gönder',
  'friendRequestSent': 'Arkadaş isteği gönderildi.',
  'blockUser': 'Kullanıcıyı engelle',
  'userBlocked': 'Kullanıcı engellendi.',
  'message': 'Mesaj',
  'sendMessage': 'Mesaj gönder',
  'messageSent': 'Mesaj gönderildi.',
  'globalChat': 'Genel sohbet',
  'globalMessage': 'Genel sohbete mesaj yaz',
  'globalChatEmpty': 'Genel sohbette henüz mesaj yok.',
  'openProfile': 'Profili aç',
  'publicProfile': 'Kullanıcı profili',
  'publicProfileSubtitle': 'Herkese açık koleksiyon, yorumlar ve beğeniler.',
  'publicCollection': 'Herkese açık koleksiyon',
  'publicCollectionEmpty': 'Açık koleksiyon yok',
  'publicCollectionEmptyBody': 'Bu kullanıcının herkese açık koleksiyon parçası henüz yok.',
  'like': 'Beğen',
  'liked': 'Beğenildi.',
  'proSubtitle': 'Sunucu tarafından doğrulanan reklamsız üyelik.',
  'proBenefits': 'Pro avantajları',
  'noAds': 'Android ve webde reklamsız kullanım',
  'advancedStats': 'Gelişmiş koleksiyon istatistikleri',
  'profileShowcase': 'Daha geniş profil vitrini',
  'powerFilters': 'Daha güçlü filtreler',
  'monthly': 'Aylık',
  'yearly': 'Yıllık',
  'playBilling': 'Play Billing',
  'serverVerified': 'Sunucu doğrulamalı',
  'bestCollectors': 'Düzenli koleksiyonerler için iyi seçenek',
  'connectBilling': 'Google Play Billing bağla',
  'monetizationReady': 'Reklam ve Pro hazırlığı',
  'adPlacementList': 'Pro olmayanlarda katalog listesi altında banner alanı.',
  'adPlacementDetail': 'Detay sayfalarında içerikten sonra rahatsız etmeyen reklam alanı.',
  'proServerCheck': 'Pro durumu yayında sadece sunucu doğrulamasıyla açılacak.',
  'adPlaceholder': 'Reklam alanı. Gerçek AdMob ID eklenene kadar reklam SDK kapalı kalır.',
  'adminSubtitle': 'Katalog düzenleme, görsel URL önizleme ve moderasyon araçları.',
  'adminOnly': 'Admin erişimi gerekli',
  'adminOnlyBody': 'Bu bölüm sadece admin rolüne sahip hesaplarda görünür.',
  'adminCatalog': 'Katalog yönetimi',
  'editEntry': 'Kaydı düzenle',
  'editingEntry': 'Düzenleniyor',
  'cancelEdit': 'Düzenlemeyi iptal et',
  'deleteEntry': 'Kaydı sil',
  'imagePreview': 'Görsel önizleme',
  'pasteImageUrl': 'Güvenli görsel URL yapıştır',
  'savedEntriesImage': 'Kaydedilen parçalar katalogda link olarak değil, görsel olarak görünür.',
  'moderationQueue': 'Moderasyon sırası',
  'noReports': 'Henüz rapor yok',
  'noReportsBody': 'Raporlanan yorumlar, profiller ve görseller burada görünür.',
  'openTarget': 'Hedefi aç',
  'markReviewing': 'İncelemede',
  'dismissReport': 'Reddet',
  'resolveReport': 'Raporu çözüldü işaretle',
  'legalSubtitle': 'DollDex Collector uyumluluk sayfası',
  'privacyBody': 'Son güncelleme: 13 Haziran 2026\n\nDollDex Collector, koleksiyon kataloglama ve topluluk özellikleri sunmak için hesap bilgilerini, Google oturum açma kimliğini, e-posta adresini, profil adını, profil fotoğrafını, benzersiz kullanıcı adını, doğum yılına dayalı yaş uygunluğu bilgisini, koleksiyon kayıtlarını, yorumları, beğenileri, raporları, arkadaşlık/engelleme ilişkilerini, mesaj içeriklerini, moderasyon kayıtlarını ve uygulama kalite verilerini işler.\n\nVeriler; hesabını oluşturmak, koleksiyonunu cihazların arasında senkronize etmek, diğer kullanıcılarla etkileşim kurmanı sağlamak, güvenlik ve moderasyon yapmak, kötüye kullanımı önlemek, yasal taleplere yanıt vermek ve isteğe bağlı Pro/abonelik özelliklerini doğrulamak için kullanılır.\n\nDollDex Collector en az 13 yaşındaki kullanıcılar içindir. Hesap kurulumunda tam doğum tarihi yerine doğum yılı alınır. Yaş sınırını karşılamayan kullanıcılar sosyal özellikleri kullanamaz.\n\nUygulama Google Firebase servislerini kullanır. Veriler Firebase Authentication ve Cloud Firestore içinde saklanabilir. Yetkili yöneticiler yalnızca destek, güvenlik, moderasyon ve yasal gereklilikler için gerekli verilere erişir.\n\nKullanıcılar hesap silme talebini uygulama içinden gönderebilir. Talep sonrasında hesap, profil ve koleksiyon verileri makul süre içinde silinir veya anonimleştirilir. Güvenlik, dolandırıcılık önleme, ödeme uyuşmazlığı, moderasyon geçmişi ya da yasal zorunluluk varsa sınırlı kayıtlar gerekli süre boyunca saklanabilir.\n\nDollDex Collector çocuklara yönelik resmi bir marka uygulaması değildir ve üçüncü taraf oyuncak markalarıyla bağlantılı değildir. Kullanıcılar telif hakkı, kişisel veri ve topluluk kurallarına uygun içerik paylaşmaktan sorumludur.',
  'termsBody': 'Son güncelleme: 13 Haziran 2026\n\nDollDex Collector; bebek, karakter, set, pet ve aksesuar koleksiyonlarını takip etmek ve toplulukla paylaşmak için sunulan bağımsız bir koleksiyon uygulamasıdır. Uygulama herhangi bir oyuncak markasının resmi ürünü değildir.\n\nUygulamayı kullanmak için en az 13 yaşında olmalı, doğru yaş uygunluğu bilgisi vermeli, benzersiz kullanıcı adını kurmalı ve bu koşulları kabul etmelisin.\n\nKullanıcılar; taciz, nefret söylemi, tehdit, dolandırıcılık, spam, güvenli olmayan bağlantı, yetişkin içerik, kişisel veri ifşası, telif hakkı ihlali ve yanıltıcı katalog bilgisi paylaşamaz. Koleksiyon, yorum, profil, mesaj ve görsel içeriklerinden paylaşan kullanıcı sorumludur.\n\nDollDex Collector; kuralları ihlal eden içerikleri kaldırabilir, raporları inceleyebilir, hesapları sınırlayabilir, askıya alabilir veya silebilir. Topluluk güvenliği ve yasal uyum için bazı kayıtlar saklanabilir.\n\nKatalog bilgileri topluluk katkısıyla gelişebilir. Uygulama katalog verilerinin hatasız, eksiksiz veya resmi olduğunu garanti etmez. Ticaret/satış özellikleri kullanılırsa kullanıcılar kendi anlaşmalarından, ödeme ve gönderim risklerinden sorumludur.\n\nUygulama zaman zaman değişebilir, bazı özellikler ücretli Pro üyelik veya reklam destekli kullanım gerektirebilir. Ödeme özellikleri etkinleştiğinde ilgili mağaza kuralları ve abonelik koşulları geçerli olur.\n\nBu koşulları kabul etmiyorsan uygulamayı kullanmamalısın.',
  'deleteBody': 'Hesabının silinmesini talep ettiğinde profil, kullanıcı adı, koleksiyon, yorum, sosyal ilişki ve mesaj verilerinin silinmesi veya anonimleştirilmesi için işlem başlatılır. Güvenlik, moderasyon, ödeme uyuşmazlığı veya yasal zorunluluk nedeniyle sınırlı kayıtlar gerekli süre boyunca saklanabilir.',
  'notificationsSubtitle': 'Mesajlar, yorumlar, takipler, raporlar ve Pro güncellemeleri.',
  'noNotifications': 'Henüz bildirim yok',
  'noNotificationsBody': 'Sosyal etkileşimleriniz (takip, mesaj, arkadaşlık) ve duyurular burada görünecektir.',
  'commentAdded': 'yorum eklendi',
  'catalogEntrySaved': 'katalog kaydı kaydedildi',
  'collectionUpdated': 'koleksiyon güncellendi',
  'entryNotFound': 'Katalog parçası bulunamadı',
  'entryNotFoundBody': 'Bu parça kaldırılmış veya henüz hazır olmayabilir.',
  'wikiPlaceholder': 'Wiki detayları, bağlı karakterler, set içerikleri, petler ve aksesuarlar burada görünecek.',
  'commentPlaceholder': 'Koleksiyoner notları ve paylaşılan parça linkleri burada görünecek.',
  'signInNeedsFirebase': 'Giriş için önce Firebase kurulumu gerekiyor.',
  'signInSuccess': 'Google hesabın bağlandı.',
  'signInCancelled': 'Google girişi iptal edildi.',
  'signInFailed': 'Google girişi başarısız:',
  'signedIn': 'Giriş yapıldı.',
  'signOut': 'Çıkış yap',
  'signOutFailed': 'Çıkış başarısız:',
  'reportSaved': 'Rapor kaydedildi.',
  'markedAs': 'olarak işaretlendi.',
  'templateCharacterName': 'Karakter profili',
  'templateCharacterSubtitle': 'Wiki kayıt şablonu',
  'templateCharacterDescription': 'Karakter sayfaları bebekleri, petleri ve aksesuarları birbirine bağlar.',
  'templateDollName': 'Oyuncak Bebek',
  'templateDollSubtitle': 'Sahibim, istiyorum, takas',
  'templateDollDescription': 'Oyuncak bebekler koleksiyon parçası olarak takip edilir.',
  'templatePetName': 'Pet arkadaşı',
  'templatePetSubtitle': 'Karaktere bağlı',
  'templatePetDescription': 'Petler karakterlere ve bebek sürümlerine bağlanabilir.',
  'templateAccessoryName': 'Aksesuar parçası',
  'templateAccessorySubtitle': 'Set tamamlama parçası',
  'templateAccessoryDescription': 'Aksesuarlar kullanıcıların detaylı setleri tamamlamasına yardım eder.',
  'typeCharacter': 'Karakter',
  'typeDoll': 'Bebek',
  'typeSet': 'Set',
  'typePet': 'Pet',
  'typeAccessory': 'Aksesuar',
  'statusOwned': 'sahibim',
  'statusWanted': 'istiyorum',
  'statusTrade': 'takas',
  'statusSelling': 'satılık',
};

const _en = {
  'appName': 'DollDex Collector',
  'notifications': 'Notifications',
  'social': 'Social',
  'theme': 'Theme',
  'catalog': 'Catalog',
  'collection': 'Collection',
  'profile': 'Profile',
  'pro': 'Pro',
  'admin': 'Admin',
  'catalogSubtitle': 'Characters, dolls, sets, pets and accessories in one place.',
  'searchHint': 'Search by character, set or item',
  'characters': 'Characters',
  'all': 'All',
  'filter': 'Filter',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'allConditions': 'All conditions',
  'dolls': 'Dolls',
  'sets': 'Sets',
  'pets': 'Pets',
  'accessories': 'Accessories',
  'owned': 'Owned',
  'want': 'Want',
  'report': 'Report',
  'addToCollection': 'Add to collection',
  'comments': 'Comments',
  'commentHint': 'Share a note or paste a related item link',
  'postComment': 'Post comment',
  'reportComment': 'Report comment',
  'collectionSubtitle': 'Track owned, wanted, trade and selling pieces.',
  'wanted': 'Wanted',
  'trade': 'Trade',
  'selling': 'Selling',
  'yourShelfReady': 'Your shelf is ready',
  'yourShelfBody': 'Add items from the catalog to start building your collection.',
  'quantityShort': 'Qty',
  'removeFromCollection': 'Remove from collection',
  'removeCollectionConfirm': 'Are you sure you want to remove this item from your collection?',
  'noCollectionFilterResults': 'No items in this filter',
  'noCollectionFilterResultsBody': 'Choose another collection status.',
  'noCatalogResults': 'No results found',
  'noCatalogResultsBody': 'Try changing the search or filters.',
  'profileSubtitle': 'Public showcase, privacy controls and account tools.',
  'profileStats': 'Profile summary',
  'profileShowcaseTitle': 'Profile showcase',
  'profileShowcaseEmpty': 'Items from your collection will appear here.',
  'collectorAccount': 'Collector account',
  'signInBody': 'Sign in to sync your collection, wishlist and profile.',
  'continueGoogle': 'Continue with Google',
  'accountTools': 'Account tools',
  'privacyPolicy': 'Privacy policy',
  'privacyRequired': 'Required for Google Play and web.',
  'termsOfUse': 'Terms of use',
  'termsRequired': 'App rules and user responsibilities.',
  'deleteAccount': 'Delete account request',
  'deleteRequired': 'Required inside the app and on the web.',
  'completeProfileRequired': 'Profile setup required',
  'completeProfileBody': 'Complete your unique username and age eligibility before using social features.',
  'username': 'Username',
  'usernameRules': '3-15 characters: lowercase letters, numbers and underscore.',
  'usernameInvalid': 'Username must be 3-15 characters and can only use letters, numbers and underscore.',
  'usernameTaken': 'This username is already taken.',
  'usernameChangeWarning': 'After setting your username, you can change it only once every 6 months.',
  'usernameChangeLocked': 'Username can only be changed once every 6 months.',
  'birthYear': 'Birth year',
  'birthYearInvalid': 'Enter a valid birth year.',
  'ageRequirement': 'You must be at least 13 years old to use DollDex Collector.',
  'ageTooYoung': 'Profile setup cannot be completed because of the age requirement.',
  'acceptPrivacy': 'I have read and accept the privacy policy.',
  'acceptTerms': 'I have read and accept the terms of use.',
  'acceptPoliciesRequired': 'You must accept the privacy policy and terms of use to continue.',
  'saveProfile': 'Complete profile',
  'profileSaved': 'Profile completed.',
  'profileSaveFailed': 'Profile could not be saved:',
  'avatarStudio': 'Avatar studio',
  'avatarStudioBody': 'Avatars and neon frames are exclusive to Pro members. Customize your gothic profile!',
  'proFrames': 'Pro frame colors',
  'proFramesLocked': 'Frame colors are available for Pro users.',
  'deleteReason': 'Deletion reason or note',
  'sendDeleteRequest': 'Send deletion request',
  'deleteRequestSaved': 'Your account deletion request was saved.',
  'deleteRequestFailed': 'Deletion request could not be sent:',
  'socialSubtitle': 'Search users, add friends, block, send messages and join the global chat.',
  'socialSignInRequired': 'Sign in with Google to use social features.',
  'userSearch': 'User search',
  'searchUsername': 'Search username',
  'search': 'Search',
  'noUsersFound': 'No users found yet.',
  'socialSearchFailed': 'User search failed:',
  'sendFriendRequest': 'Send friend request',
  'friendRequestSent': 'Friend request sent.',
  'blockUser': 'Block user',
  'userBlocked': 'User blocked.',
  'message': 'Message',
  'sendMessage': 'Send message',
  'messageSent': 'Message sent.',
  'globalChat': 'Global chat',
  'globalMessage': 'Write to global chat',
  'globalChatEmpty': 'No messages in global chat yet.',
  'openProfile': 'Open profile',
  'publicProfile': 'User profile',
  'publicProfileSubtitle': 'Public collection, comments and likes.',
  'publicCollection': 'Public collection',
  'publicCollectionEmpty': 'No public collection',
  'publicCollectionEmptyBody': 'This user does not have public collection items yet.',
  'like': 'Like',
  'liked': 'Liked.',
  'proSubtitle': 'Server-verified membership with an ad-free experience.',
  'proBenefits': 'Pro benefits',
  'noAds': 'No ads across Android and web',
  'advancedStats': 'Advanced collection stats',
  'profileShowcase': 'Expanded profile showcase',
  'powerFilters': 'More powerful filters',
  'monthly': 'Monthly',
  'yearly': 'Yearly',
  'playBilling': 'Play Billing',
  'serverVerified': 'Server verified',
  'bestCollectors': 'Best for regular collectors',
  'connectBilling': 'Connect Google Play Billing',
  'monetizationReady': 'Ads and Pro readiness',
  'adPlacementList': 'Banner area below catalog lists for non-Pro users.',
  'adPlacementDetail': 'Non-disruptive ad area after detail page content.',
  'proServerCheck': 'Pro status will only unlock after server verification.',
  'adPlaceholder': 'Ad area. The ad SDK stays disabled until a real AdMob ID is added.',
  'adminSubtitle': 'Catalog editing, image URL preview and moderation tools.',
  'adminOnly': 'Admin access required',
  'adminOnlyBody': 'This section is only visible for accounts with the admin role.',
  'adminCatalog': 'Catalog management',
  'editEntry': 'Edit entry',
  'editingEntry': 'Editing',
  'cancelEdit': 'Cancel edit',
  'deleteEntry': 'Delete entry',
  'imagePreview': 'Image preview',
  'pasteImageUrl': 'Paste a secure image URL',
  'savedEntriesImage': 'Saved entries will show the picture in catalog cards and detail pages, not the raw URL.',
  'moderationQueue': 'Moderation queue',
  'noReports': 'No reports yet',
  'noReportsBody': 'Reported comments, profiles and images will appear here.',
  'openTarget': 'Open target',
  'markReviewing': 'Reviewing',
  'dismissReport': 'Dismiss',
  'resolveReport': 'Mark report resolved',
  'legalSubtitle': 'DollDex Collector compliance page',
  'privacyBody': 'Last updated: June 13, 2026\n\nDollDex Collector processes account information, Google sign-in identifiers, email address, profile name, profile photo, unique username, birth-year based age eligibility, collection entries, comments, likes, reports, friend/block relationships, message content, moderation records and app quality data to provide collection tracking and community features.\n\nData is used to create your account, sync your collection across devices, enable interaction with other users, provide safety and moderation, prevent abuse, respond to legal requests and verify optional Pro/subscription features.\n\nDollDex Collector is for users who are at least 13 years old. During setup, the app collects birth year instead of full date of birth. Users who do not meet the age requirement cannot use social features.\n\nThe app uses Google Firebase services. Data may be stored in Firebase Authentication and Cloud Firestore. Authorized administrators access data only when needed for support, safety, moderation or legal compliance.\n\nUsers can request account deletion from inside the app. After a request, account, profile and collection data is deleted or anonymized within a reasonable period. Limited records may be retained when required for safety, fraud prevention, payment disputes, moderation history or legal obligations.\n\nDollDex Collector is not an official brand app for children and is not affiliated with third-party toy brands. Users are responsible for sharing content that respects copyright, personal data and community rules.',
  'termsBody': 'Last updated: June 13, 2026\n\nDollDex Collector is an independent collection app for tracking and sharing doll, character, set, pet and accessory collections. The app is not an official product of any toy brand.\n\nTo use the app, you must be at least 13 years old, provide accurate age eligibility information, set up a unique username and accept these terms.\n\nUsers may not share harassment, hate speech, threats, scams, spam, unsafe links, adult content, personal data disclosures, copyright-infringing content or misleading catalog information. Users are responsible for the collection, comment, profile, message and image content they share.\n\nDollDex Collector may remove content that violates rules, review reports, limit accounts, suspend accounts or delete accounts. Some records may be retained for community safety and legal compliance.\n\nCatalog information may improve through community contributions. The app does not guarantee that catalog data is error-free, complete or official. If trade or sale features are used, users are responsible for their own agreements, payment risks and shipping risks.\n\nThe app may change over time, and some features may require a paid Pro membership or ad-supported use. When payment features are enabled, the relevant store rules and subscription terms apply.\n\nIf you do not accept these terms, you should not use the app.',
  'deleteBody': 'When you request account deletion, deletion or anonymization starts for your profile, username, collection, comments, social relationships and message data. Limited records may be retained when required for safety, moderation, payment disputes or legal obligations.',
  'notificationsSubtitle': 'Messages, comments, follows, reports and Pro updates.',
  'noNotifications': 'No notifications yet',
  'noNotificationsBody': 'Social interactions (follows, messages, friends) and announcements will appear here.',
  'commentAdded': 'comment added',
  'catalogEntrySaved': 'catalog entry saved',
  'collectionUpdated': 'collection updated',
  'entryNotFound': 'Catalog entry not found',
  'entryNotFoundBody': 'This item may have been removed or is not available yet.',
  'wikiPlaceholder': 'Wiki details, linked characters, set contents, pets and accessories will appear here.',
  'commentPlaceholder': 'This page will show collector notes and shared item links.',
  'signInNeedsFirebase': 'Firebase setup is required before sign-in.',
  'signInSuccess': 'Your Google account is connected.',
  'signInCancelled': 'Google sign-in was cancelled.',
  'signInFailed': 'Google sign-in failed:',
  'signedIn': 'Signed in.',
  'signOut': 'Sign out',
  'signOutFailed': 'Sign-out failed:',
  'reportSaved': 'Report saved.',
  'markedAs': 'marked as',
  'templateCharacterName': 'Character Profile',
  'templateCharacterSubtitle': 'Wiki entry template',
  'templateCharacterDescription': 'Character pages will connect dolls, pets and accessories.',
  'templateDollName': 'Doll Release',
  'templateDollSubtitle': 'Owned, wanted, trade',
  'templateDollDescription': 'Doll releases will be tracked as collection pieces.',
  'templatePetName': 'Pet Companion',
  'templatePetSubtitle': 'Linked to character',
  'templatePetDescription': 'Pets can connect to characters and doll releases.',
  'templateAccessoryName': 'Accessory Piece',
  'templateAccessorySubtitle': 'Set completion item',
  'templateAccessoryDescription': 'Accessories help users complete detailed sets.',
  'typeCharacter': 'Character',
  'typeDoll': 'Doll',
  'typeSet': 'Set',
  'typePet': 'Pet',
  'typeAccessory': 'Accessory',
  'statusOwned': 'owned',
  'statusWanted': 'wanted',
  'statusTrade': 'trade',
  'statusSelling': 'selling',
};
